// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	MoodTag       string                 `protobuf:"bytes,4,opt,name=mood_tag,json=moodTag,proto3" json:"mood_tag,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Available     bool                   `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetMoodTag() string {
	if x != nil {
		return x.MoodTag
	}
	return ""
}

func (x *ProductResponse) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_proto_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *StockItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ValidateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateStockRequest) Reset() {
	*x = ValidateStockRequest{}
	mi := &file_proto_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStockRequest) ProtoMessage() {}

func (x *ValidateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStockRequest.ProtoReflect.Descriptor instead.
func (*ValidateStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UnavailableItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnavailableItem) Reset() {
	*x = UnavailableItem{}
	mi := &file_proto_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnavailableItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnavailableItem) ProtoMessage() {}

func (x *UnavailableItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnavailableItem.ProtoReflect.Descriptor instead.
func (*UnavailableItem) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *UnavailableItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UnavailableItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ValidateStockResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllAvailable     bool                   `protobuf:"varint,1,opt,name=all_available,json=allAvailable,proto3" json:"all_available,omitempty"`
	UnavailableItems []*UnavailableItem     `protobuf:"bytes,2,rep,name=unavailable_items,json=unavailableItems,proto3" json:"unavailable_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateStockResponse) Reset() {
	*x = ValidateStockResponse{}
	mi := &file_proto_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStockResponse) ProtoMessage() {}

func (x *ValidateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStockResponse.ProtoReflect.Descriptor instead.
func (*ValidateStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateStockResponse) GetAllAvailable() bool {
	if x != nil {
		return x.AllAvailable
	}
	return false
}

func (x *ValidateStockResponse) GetUnavailableItems() []*UnavailableItem {
	if x != nil {
		return x.UnavailableItems
	}
	return nil
}

type ReduceStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*StockItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceStockRequest) Reset() {
	*x = ReduceStockRequest{}
	mi := &file_proto_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceStockRequest) ProtoMessage() {}

func (x *ReduceStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceStockRequest.ProtoReflect.Descriptor instead.
func (*ReduceStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *ReduceStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReduceStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReduceStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceStockResponse) Reset() {
	*x = ReduceStockResponse{}
	mi := &file_proto_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceStockResponse) ProtoMessage() {}

func (x *ReduceStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceStockResponse.ProtoReflect.Descriptor instead.
func (*ReduceStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *ReduceStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReduceStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_product_product_proto protoreflect.FileDescriptor

const file_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product/product.proto\x12\aproduct\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x9a\x01\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x19\n" +
	"\bmood_tag\x18\x04 \x01(\tR\amoodTag\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\bR\tavailable\"F\n" +
	"\tStockItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"@\n" +
	"\x14ValidateStockRequest\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.product.StockItemR\x05items\"H\n" +
	"\x0fUnavailableItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x83\x01\n" +
	"\x15ValidateStockResponse\x12#\n" +
	"\rall_available\x18\x01 \x01(\bR\fallAvailable\x12E\n" +
	"\x11unavailable_items\x18\x02 \x03(\v2\x18.product.UnavailableItemR\x10unavailableItems\"Y\n" +
	"\x12ReduceStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.product.StockItemR\x05items\"I\n" +
	"\x13ReduceStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xee\x01\n" +
	"\x0eProductService\x12B\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x18.product.ProductResponse\x12N\n" +
	"\rValidateStock\x12\x1d.product.ValidateStockRequest\x1a\x1e.product.ValidateStockResponse\x12H\n" +
	"\vReduceStock\x12\x1b.product.ReduceStockRequest\x1a\x1c.product.ReduceStockResponseB4Z2github.com/Bimidu/ctse-order-service/proto/productb\x06proto3"

var (
	file_proto_product_product_proto_rawDescOnce sync.Once
	file_proto_product_product_proto_rawDescData []byte
)

func file_proto_product_product_proto_rawDescGZIP() []byte {
	file_proto_product_product_proto_rawDescOnce.Do(func() {
		file_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)))
	})
	return file_proto_product_product_proto_rawDescData
}

var file_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_product_product_proto_goTypes = []any{
	(*GetProductRequest)(nil),     // 0: product.GetProductRequest
	(*ProductResponse)(nil),       // 1: product.ProductResponse
	(*StockItem)(nil),             // 2: product.StockItem
	(*ValidateStockRequest)(nil),  // 3: product.ValidateStockRequest
	(*UnavailableItem)(nil),       // 4: product.UnavailableItem
	(*ValidateStockResponse)(nil), // 5: product.ValidateStockResponse
	(*ReduceStockRequest)(nil),    // 6: product.ReduceStockRequest
	(*ReduceStockResponse)(nil),   // 7: product.ReduceStockResponse
}
var file_proto_product_product_proto_depIdxs = []int32{
	2, // 0: product.ValidateStockRequest.items:type_name -> product.StockItem
	4, // 1: product.ValidateStockResponse.unavailable_items:type_name -> product.UnavailableItem
	2, // 2: product.ReduceStockRequest.items:type_name -> product.StockItem
	0, // 3: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	3, // 4: product.ProductService.ValidateStock:input_type -> product.ValidateStockRequest
	6, // 5: product.ProductService.ReduceStock:input_type -> product.ReduceStockRequest
	1, // 6: product.ProductService.GetProduct:output_type -> product.ProductResponse
	5, // 7: product.ProductService.ValidateStock:output_type -> product.ValidateStockResponse
	7, // 8: product.ProductService.ReduceStock:output_type -> product.ReduceStockResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_product_product_proto_init() }
func file_proto_product_product_proto_init() {
	if File_proto_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_product_proto_goTypes,
		DependencyIndexes: file_proto_product_product_proto_depIdxs,
		MessageInfos:      file_proto_product_product_proto_msgTypes,
	}.Build()
	File_proto_product_product_proto = out.File
	file_proto_product_product_proto_goTypes = nil
	file_proto_product_product_proto_depIdxs = nil
}
